# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field, RootModel


class ContainerStatus(BaseModel):
    running: bool
    ready: bool


class VolumeStatus(BaseModel):
    exists: bool


class ArchiveLatest(BaseModel):
    archive_key: str = Field(..., description='S3 key of the archive')
    archive_op_id: str = Field(..., description='Archive operation ID')
    archived_at: str = Field(..., description='ISO 8601 timestamp')


class ArchiveStatus(BaseModel):
    latest: ArchiveLatest | None = None


class RestoreLast(BaseModel):
    source_archive_key: str = Field(..., description='Archive that was restored from')
    restore_op_id: str = Field(..., description='Restore operation ID')
    restored_at: str = Field(..., description='ISO 8601 timestamp')


class RestoreStatus(BaseModel):
    last: RestoreLast | None = None


class ErrorLast(BaseModel):
    operation: str = Field(..., description='ARCHIVING or RESTORING')
    code: str = Field(..., description='Error code or exit code as string')
    error_at: str = Field(..., description='ISO 8601 timestamp')
    archive_op_id: str | None = Field(None, description='For archive errors')
    restore_op_id: str | None = Field(None, description='For restore errors')


class ErrorStatus(BaseModel):
    last: ErrorLast | None = None


class WorkspaceState(BaseModel):
    workspace_id: str
    container: ContainerStatus | None = None
    volume: VolumeStatus | None = None
    archive: ArchiveStatus | None = None
    restore: RestoreStatus | None = None
    error: ErrorStatus | None = None


class UpstreamInfo(BaseModel):
    hostname: str
    port: int


class GCResult(BaseModel):
    deleted_count: int
    deleted_keys: list[str]


class OperationStatusValue(StrEnum):
    in_progress = 'in_progress'
    completed = 'completed'
    already_exists = 'already_exists'
    already_running = 'already_running'
    already_stopped = 'already_stopped'
    already_deleted = 'already_deleted'


class ObserveResponse(BaseModel):
    workspaces: list[WorkspaceState]


class OperationResponse(BaseModel):
    status: OperationStatusValue
    workspace_id: str


class StartRequest(BaseModel):
    image: str | None = None


class ArchiveRequest(BaseModel):
    archive_op_id: str


class ArchiveResponse(BaseModel):
    status: OperationStatusValue
    workspace_id: str
    archive_key: str


class RestoreRequest(BaseModel):
    archive_key: str
    restore_op_id: str


class RestoreResponse(BaseModel):
    status: OperationStatusValue
    workspace_id: str
    restore_marker: str


class UpstreamResponse(BaseModel):
    hostname: str
    port: int
    url: str


class ProtectedWorkspace(RootModel[tuple[str, str]]):
    root: tuple[str, str] = Field(..., max_length=2, min_length=2)


class GCRequest(BaseModel):
    archive_keys: list[str] = Field(
        ..., description='Direct archive_key column values (RESTORING target)'
    )
    protected_workspaces: list[ProtectedWorkspace] = Field(
        ..., description='(ws_id, archive_op_id) tuples for path calculation'
    )
    retention_count: int | None = Field(
        3, description='Number of archives to keep per workspace'
    )


class GCResponse(BaseModel):
    deleted_count: int
    deleted_keys: list[str]
